[package]
name = "dynamic-grid"
version = "0.1.0"
authors = ["zitoun brahim <brahim.zitoun@crisalid.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
assert_matches = "1.5.0"